name: Stylelint Check

on:
  pull_request:
    branches: [main, develop, release/*]

jobs:
  stylelint:
    name: Run Stylelint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Run Stylelint
        id: stylelint
        run: |
          npx stylelint "**/*.css" "**/*.scss" "**/*.less" \
            --formatter verbose \
            --report-needless-disables \
            --max-warnings 0 \
            > stylelint_report.txt
          echo "exit_code=$?" >> $GITHUB_OUTPUT

      - name: Upload Stylelint report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: stylelint-report
          path: stylelint_report.txt

      - name: Fail if Stylelint found errors
        if: steps.stylelint.outputs.exit_code != '0'
        run: |
          echo "Stylelint found errors. Please check the stylelint_report.txt artifact for details."
          exit 1
