name: Stylelint Check

on:
  pull_request:
    branches: [main, develop, release/*] # Adjust these to your main development branches

jobs:
  stylelint:
    name: Run Stylelint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' # Use the latest LTS version of Node.js

      - name: Install dependencies
        run: npm ci # Or yarn install --frozen-lockfile if you use Yarn

      - name: Run Stylelint (Verbose Output)
        run: npx stylelint "**/*.css" "**/*.scss" "**/*.less" --formatter verbose --report-needless-disables --max-warnings 0 > stylelint_report.txt
        # Adjust the file patterns to match your CSS/style files

      - name: Upload Stylelint report for PR review
        uses: actions/upload-artifact@v4
        if: failure() # Only upload if the Stylelint check fails
        with:
          name: stylelint-report
          path: stylelint_report.txt

      - name: Fail the workflow if Stylelint found errors
        if: failure()
        run: echo "Stylelint found errors. Please check the 'stylelint-report' artifact." && exit 1
