name: Stylelint Check

on:
  pull_request:
    branches: [main, develop, release/*] # Adjust these to your main development branches

jobs:
  stylelint:
    name: Run Stylelint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' # Use the latest LTS version of Node.js

      - name: Install dependencies
        run: npm install # Changed from npm ci

      - name: Upgrade stylelint-declaration-strict-value
        run: npm install stylelint-declaration-strict-value@latest --save-dev

      - name: Run Stylelint
        id: stylelint
        run: |
          npx stylelint "**/*.css" "**/*.scss" "**/*.less" --formatter verbose --report-needless-disables --max-warnings 0
          if [ $? -ne 0 ]; then
            echo "Stylelint found errors."
            exit 1
          fi
        # Adjust the file patterns to match your CSS/style files

      - name: Upload Stylelint report for PR review (if errors exist)
        if: steps.stylelint.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: stylelint-report
          path: stylelint_report.txt # This file is not being created in the current setup

      - name: Fail the workflow if Stylelint found errors
        if: steps.stylelint.outcome == 'failure'
        run: echo "Stylelint found errors. Please check the workflow logs for details." && exit 1
